version: "3.8"
services:
  mongodb:
    image: mongo:latest
    container_name: mongo-workshop
    ports:
      - "27017:27017"  # Expose MongoDB on port 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminpass

    volumes:
      - ./mongo-data:/data/db

    networks:
      - mynetwork

  mongorestore:
      image: mongo:latest
      depends_on:
        - mongodb
      volumes:
        - ./dump:/dump
        - ./restore.sh:/docker-entrypoint-initdb.d/restore.sh
      entrypoint: [ "bash", "/docker-entrypoint-initdb.d/restore.sh" ]
      networks:
        - mynetwork
  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - mongodb  
    networks:
      - mynetwork
    environment:
      - MONGODB_URI=mongodb://admin:adminpass@mongodb:27017/PPP?authSource=admin
      - API_URI=frontend
    ports:
      - "5555:5555"  
    volumes: 
      - logs:/app/logs
      - ./backend:/app/backend
      - /app/backend/node_modules

  frontend:
    build: ./frontend
    ports: 
      - '3000:80'
    networks:
      - mynetwork
    volumes: 
      - ./frontend:/app/frontend
    environment:
      - VITE_API_URL=http://backend:5555
    stdin_open: true
    tty: true
    depends_on: 
      - backend

volumes: 
  data:
  logs:
networks:
  mynetwork:
    driver: bridge
